apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t82107479-ingress
spec:
  ingressClassName: ingress-internal
  rules:
  - host: dev.82107479.ce-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: t82107479-service
            port:
              number: 8080
        pathType: Prefix
